### ISSUE TITLE
Pixie file extension

### ISSUE THREAD

**Issue by andrewchambers** [pixie-lang/pixie#33]
Are there any opinions on what the source file extension should be? Currently it seems to have defaulted to .lisp. Would be a simple matter to change it if one is chosen.

.pixie, .pix are strong contenders in my opinion. Any changes might go nicely with syntax files for at least emacs, vim and sublime text in a folder or top level repo.

**Comment by opyate** [comment]
```.pxi``` is [already taken](http://docs.cython.org/src/reference/language_basics.html).
I'd like both modes in Emacs, so I guess I loose auto-loading?

PS 3-character extensions is like running out of IPv4 address space. Perhaps reconsider ```.pixie```? Besides, some Lisps use ```.lisp```.

**Comment by andrewchambers** [comment]
Using .lisp is a bad idea, it is already taken by lisps without clojure extensions. I vote we change it to '.cython'. I really don't get why cython chose '.pxi'.

**Comment by opyate** [comment]
> Using .lisp is a bad idea, it is already taken by lisps without clojure extensions.

I didn't mean for Pixie to adopt ```.lisp``` - it was an example of other Lisps going beyond the 3-character limitation.

> I vote we change it to '.cython'.

Sorry, I don't understand. 

> I really don't get why cython chose '.pxi'.

Cython is a derivative of [Pyrex](https://en.wikipedia.org/wiki/Pyrex_(programming_language)). I'm guessing the ```px``` is from Pyrex, and the ```i``` is because it's an ```include``` file.

> In all seriousness, I think that is a stupid reason to change it and it is fine as it is.

```.pxi``` clashing with a language which predates it by 7 years is hardly a stupid reason, no?

**Comment by andrewchambers** [comment]
Wanting to edit pixie and cython files in tandem in emacs but not being able to just manually set the syntax highlighting is a poor reason to change something that was decided nearly a year ago.
