### ISSUE TITLE
BigInteger writing

### ISSUE THREAD

**Issue by thomasmulvaney** [pixie-lang/pixie#345]
Currently in compiled mode only writing BigIntegers out as strings has been implemented. We should implement the other encoding as well.

**Comment by MatthewWest** [comment]
I'd like to work on this. Am I correct that the primary places this will need work are in pixie/vm/libs/pxic/writer.py and reader.py (same location)?

**Comment by thomasmulvaney** [comment]
That's correct. You should almost be able to copy whats done for `Integers`.

**Comment by MatthewWest** [comment]
There's a bit of a challenge with this one. Because BigIntegers have a potentially infinite length, rather than a set length as do ordinary integers, we have to have a way of knowing how many characters to read in as part of the BigInteger. This is similar to the problem of knowing when to end a string. Since we can't do null-terminators to end like you would in a string, I'm doing an integer first to say how many 8-bit characters represent the integer. That will allow numbers up to 2^(MAX_INTEGER), which should be large enough for almost any conceivable use.

**Comment by heyLu** [comment]
You could work around that by writing in chunks.  [Fressian](https://github.com/Datomic/fressian) does that if a string (or a byte array) is too long.

However, it's probably not necessary.  A comment indicating that there is a limit should be enough.

**Comment by thomasmulvaney** [comment]
Indicating the length sounds like a smart choice.

**Comment by MatthewWest** [comment]
For testing, are there functions I'm not finding that read and write to pxic from pxi expressions?

**Comment by thomasmulvaney** [comment]
In the `pixie-vm2` branch the pxic writer is implemented in pixie itself so it would be quite easy. Unfortunately, in `master` there isn't any obvious way to test this kind of thing nicely. You could try and expose some of the underlying rpython to pixie, but those functions would really only useful for testing I imagine.

**Comment by MatthewWest** [comment]
Ugh. That makes it difficult to test my code. I'll go through it a few more times and then submit a pull request probably, so others can catch pitfalls.

**Comment by MatthewWest** [comment]
That pull request now includes my implementation of big integer writing to pxic.

**Comment by heyLu** [comment]
Merged as part of #319.
