### ISSUE TITLE
defn/defn+

### ISSUE THREAD

**Issue by lgrapenthin** [pixie-lang/pixie#369]
This might be worth considering and discussing given that pixie doesn't intend to be a Clojure. 

When I heard that in Rust functions are private by default I immediately noticed that I am used to writing defn- by default and most of the time when coding a new ns. I think its a good design choice on the Rust side.

Idea is like this:

defn defines private functions.
defn+ defines public functions and is used less often.

Same could be done for def, but given that Clojure still has no def- this might be another area of discussion.

**Comment by arrdem** [comment]
I'm going to go ahead and disagree with this out of the gate.

Traditionally in primarily mutable languages, the concept of packages and of symbol privacy exists to create delineations between those effects which are intended to be used by users, and those effects which the implementer may find it convenient to factor out and perform elsewhere. The precise implementation of this "public" vs "true" API varies by programming language but the concept holds.

In the context of a mostly or entirely immutable language privacy especially privacy by default simply makes less sense. Because we have immutability and idempotence there really aren't operations which we could express on a datatype which we can't meaningfully and safely expose to a user. While it may be possible to write software in a mostly private style this runs the risk of hiding from a user an operation which they could safely perform and forcing them either to reinvent it or to use some combination of implementation details and reflection to get at the existing implementation.

Alternate implementations are clearly undesirable, especially for common operations which would be better served factored out either into libraries or into the standard library and there solidified. Reflection and other hackery is equally inconvenient and undesirable because it leaves users dependent on something which you as a library author expect to break with no warning.

James Reeves has repeatedly made similar arguments against var privacy on the Clojure mailing list, to which I will further appeal, as has Brandon Bloom.

**Comment by halgari** [comment]
I agree, users should prefer "private" namespaces over private vars. Put your private implementation in a namespace with a comment at the top that says "don't touch this, it could change". But don't restrict your more advanced users.

**Comment by lgrapenthin** [comment]
I consider myself an advanced user. Never have I found myself "restricted" by private function declarations. Instead, they have helped me and my devtools to understand what is part of a public API and what isn't. Creating an additional namespace just for a few private functions only used from one ns is a practice I have not tried out yet. At first glance, for most of thje use cases I encounter on a daily basis it seems overly pedantic.

@halgari So this means pixie won't have defn- as well?

**Comment by heyLu** [comment]
Pixie already has `defn-`, which sets `:private true` in the metadata.  However, we don't have `ns-publics` yet, and `ns-map` includes private vars.

**Comment by arrdem** [comment]
I would be amused to take a swing at `ns-publics`, will open a PR.

**Comment by halgari** [comment]
I'm fine with a option to make some vars private, but we should stick with public by default.

**Comment by heyLu** [comment]
@halgari I think we can close this, given we already have `defn-`.

**Comment by lgrapenthin** [comment]
I'd recommend reconsidering your choice mainly because I think this feature request is misunderstood. It is not about whether it is better style to write more public or more private functions or whether advanced users ending up restricted by private functions is a good thing or should or should not happen.

As an author, I convey to readers what is public and what isn't via function metadata and free text documentation. Obviously, the data is more reliable than the free text. As a library user I am guided by this data.

Its agreed upon that refactored libraries implement fewer functions intended for user invocation than for internal use. A public function the reader should use is a rare case and not the common case. This feature request is about reflecting this fact in the words one has to type.

Do you want your users to think about whether they really want to make a function public? Or do you want them to accidentally make functions public so that advanced users won't be restricted?

On a side note private does not have to be implemented as "can't ever be called from another namespace" - implementation is a separate concern. Whether advanced users end up restricted by that is a language implementation choice. Even Clojure has the var invoke escape hatch for advanced users, ClojureScript does not really care about invoking private vars at all.

**Comment by weavejester** [comment]
> Its agreed upon that refactored libraries implement fewer functions intended for user invocation than for internal use. A public function the reader should use is a rare case and not the common case.

Agreed upon? By whom?

**Comment by lgrapenthin** [comment]
@weavejester I find that this is a fact that can be observed on popular libraries in any language. It should be easy to validate that observation statistically. E. g. your compojure.core declares 19 private and 5 public functions.

**Comment by weavejester** [comment]
@lgrapenthin Compojure is actually the outlier, at least when it comes to projects I work on. I ran a quick check over all the Clojure projects currently on my machine, and 62% of all functions are public.

**Comment by mpenet** [comment]
Private functions also make writing test for them problematic without having to resort to hacks. I personally hate them after having had to use such hacks a number of times and as a result I am 100% in favor of letting the end user deal with that themselves ("private"/impl namespaces are imo the way to go). 

The only reason I had to resort to private vars in the past is when I didn't want them to show up in the generated docs, until the doc generation libraries implemented ways to exclude vars by other means, which is more appropriate.

**Comment by lgrapenthin** [comment]
@mpenet That is because of how their accessibility is implemented in the language you are using. Accessing a private var could emit a compiler warning and you could turn it off. You wouldn't have to add metadata in your code for sole use by doc generators then. If the feature prevents you from using it, it is likely that it is not implemented in the most useful way.

@weavejester I find it more difficult to argue for this FR now, especially if your usage represents the average pro-user. Otherwise I find it still worthy to reflect upon it.
