### ISSUE TITLE
Examples are broken

### ISSUE THREAD

**Issue by rbuchmann-fdc** [pixie-lang/pixie#452]
Hi,

with a fresh checkout and build, I can run almost none of the examples (assuming ./pixi-vm examples/foo.pxi is the way to go here)

mu-kanren.pxi -> runtimeException: :pixie.stdlib/AssertionException Var sequence is undefined
mandelbrot.pxi -> RuntimeException: :pixie.stdlib/EOFWhileReadingException Unexpected EOF while reading
tty-io-test.pxi -> RuntimeException: :pixie.io/Exception Expected a LineReader, UTF8InputStream, or BufferedInputStream

I'd like to use pixie for shell scripting, so the tty example is of particular importance to me.

**Comment by thomasmulvaney** [comment]
I have addressed the `tty-io-test.pxi` issue in #453 
Feel free to add a sequence function to stdlib as it is missing pull requests are very welcome :smile:

**Comment by rbuchmann-fdc** [comment]
tty-io-test works now, thanks! Pixie is phenomenal, just wrote a few scripts and it felt great. I'd rather not promise any contributions, but if I find time I'll definitely give it a try.

**Comment by jmglov** [comment]
Can we close this now?

**Comment by thomasmulvaney** [comment]
I suspect you'll find #436 fixes the mandelbrot issue.

**Comment by thomasmulvaney** [comment]
I'd like to close this issue but it seems like some other examples are broken. The mu-kanren example fails because `sequence` is not defined. The gen-docs example fails because it depends on hiccup. I think we should remove the gen-docs example or at least make it work without hiccup. I don't think any examples should depend on external libraries.

It looks like `sequence` was removed way back in d22b9c3deb39d5f2dd11c20a93c21c07227d97b9. I've created issue #502 for adding a sequence function back in.
