### ISSUE TITLE
fatal error: 'boost/type_traits.hpp' file not found

### ISSUE THREAD

**Issue by prairie-guy** [pixie-lang/pixie#491]
I am trying to compile Pixie (fresh from github) on OS X 10.11.3

I used Brew to add libuv, libffi, boost:
"libuv-1.7.5 already installed"
"libffi-3.0.13 already installed"
"boost-1.60.0_1 already installed"
 
In order to find libffi: I added
`export PKG_CONFIG_PATH=/usr/local/Cellar/libffi/3.0.13/lib/pkgconfig/ `

I fail with: 
```
In file included from /var/folders/0d/wg2l_wcj2nx4f85sw6lnh4rh0000gq/T//ffiqF6FM0/ffi.cpp:2:
/Users/cdaniels/local/pixie/pixie/PixieChecker.hpp:11:10: fatal error: 'boost/type_traits.hpp' file not found
#include "boost/type_traits.hpp"

```
Thanks for your help.

**Comment by thomasmulvaney** [comment]
Have you looked at #284 ? There was a solution (although not ideal) which involved a simple symlink. Hopefully someone with OSX can fix this issue in the future.

**Comment by prairie-guy** [comment]
Thanks. I had tried the symlink before. Went back and tried it again. It compiled, but failed with the test code. Maybe best to just try Pixie under Ubuntu with VMware. Probably easier/better than trying to get OS X working.

**Comment by alekcz** [comment]
By a twist of fate I now have access to OS X. It turns out upgrading to El Capitan removes your XCode command line tools. You can reinstall it by the following:

```
xcode-select --install
```
(Answer from Stack Overflow http://stackoverflow.com/questions/32898887/boost-no-longer-works-with-homebrew-on-mac-el-capitan)

Also the path to `type_traits.hpp` has changed in Boost 1.60 (which is the version homebrew will give you). So in `pixie/PixieChecker.hpp` the include path needs to change to:

```
#include "boost/tr1/type_traits.hpp"
```

I still need to check if the same is true on Ubuntu, before I do a pull request. You should be able to build with those changes in the mean time.
